config/routes.rb
Rails.application.routes.draw do

	root 'jobs#premium'

	get 'jobs/premium' # http://guides.rubyonrails.org/routing.html#crud-verbs-and-actions
	delete 'comments/:id' => 'comments#destroy', as: :comment

  	resources :jobs do
  		post 'comments' => 'comments#create'
  	end

  	get 'hello/world'

  	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :job, touch: true
  
  validates :name, presence: true
  validates :body, presence: true
  validates :job,  presence: true
end

app/models/job.rb
class Job < ApplicationRecord
	has_many :comments

	validates :title, presence: true
	validates :description, presence: true

	scope :most_recent, -> { order("created_at DESC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@job = Job.find(params[:job_id])
		@comment = @job.comments.build(comment_params)
		if @comment.save
			flash[:notice] = "Comment was created with success"
		else
			flash[:alert] = "Please fill in all fields to create a comment"
		end
		redirect_to @job
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to @comment.job, notice: "Comment destroyed with success"
	end

	private
		def comment_params
			params.require(:comment).permit(:name, :body)
		end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def world
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.most_recent.all

    respond_to do |format|
      format.html
      format.xml {render xml: @jobs}
    end
  end

  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def premium
    #@jobs = Job.where(premium: true).most_recent.all
    @jobs = Job.where(premium: true).most_recent.
      paginate(page: params[:page], per_page: 10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :premium)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
	
	def job_title(job)
		title = h(job.title)

		if job.premium
			title + content_tag(:strong, " (premium)")
		else
			title
		end
	end
end

app/views/comments/_comment.html.erb
<h4><%= comment.name %> said:</h4>
<%= simple_format comment.body %>
Sent <%= time_ago_in_words comment.created_at %> ago

<%= link_to "Destroy", comment_path(comment), method: :delete, data: {confirm: "Are you sure?"}%>

app/views/comments/_form.html.erb
<%= form_for [@job, Comment.new] do |f| %>
	<div class="field">
		<%= f.label :name%>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :body%>
		<%= f.text_area :body %>
	</div>

	<div class="actions">
		<%= f.submit "Send"%>
	</div>

<% end %>

app/views/hello/world.html.erb
<h1>Hello#world</h1>
<strong><%= Time.now %></strong>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :job_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.check_box :premium %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<% cache job do %>
  <h3>
    <%= job_title job %>
  </h3>

  <%= simple_format job.description%>

  <p>
    <%= pluralize(job.comments.size, 'comment') %>
    <td><%= link_to 'Show', job %></td>
      <td><%= link_to 'Edit', edit_job_path(job) %></td>
      <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </p>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<%= render partial: 'job', collection: @jobs, cached: true %>

<br>

<%= link_to 'New Job', new_job_path %><br/>

<%= link_to 'Página Inícial', root_path %><br/>

<%= link_to 'Todos os premiuns', jobs_premium_path%>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<p id="notice"><%= notice %></p>

<h1>Premium Jobs</h1>

<%= render partial: 'job', collection: @jobs, cached: true %>
<!-- <%= render @jobs %> -->

<%= will_paginate @jobs%>

<br>

<%= link_to 'New Job', new_job_path %><br/>

<%= link_to 'Todos os Jobs', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert" ><%= alert %></p>

<h1><%= job_title @job %></h1>

<%= simple_format @job.description%>

<p>
	<%= pluralize(@job.comments.size, 'comment') %>
    <%= link_to 'Edit', edit_job_path(@job) %> |
	<%= link_to 'Back', jobs_path %>
</p>

<h2>Send a new comment</h2>
<%= render partial: 'comments/form' %>

<h2>Comments</h2>
<%= render @job.comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>